const dataAtual = new Date()
console.log(dataAtual.toString())
console.log(dataAtual.getDate())
console.log(dataAtual.getFullYear())
console.log(dataAtual.getDay() + 1 )
console.log(dataAtual.getMonth())
console.log(dataAtual.getMilliseconds())